### PR TITLE
fix: register Ash timestamps with Ecto's autogenerate system

### LINKED ISSUE #769: Actor option ignored/overwritten.
It seems that when you provide the `actor` option to code interfaces or API action functions it is ignored, and only setting it with `Ash.Changeset.for_(create|read|update)` works.  Maybe not always?

See https://elixirforum.com/t/relate-actor-results-in-could-not-relate-to-actor-as-no-actor-was-found-and-allow-nil-is-false/59534/3

### PR DESCRIPTION
**Pull request by RylandBangerter85**
Ash resources generate Ecto schemas automatically, but create_timestamp/update_timestamp attributes were not registered with Ecto's autogenerate system. This meant __schema__(:autogenerate_fields) returned [] and Repo.insert/1 left timestamp fields as nil.

This wires Ash's timestamp attributes into Ecto's :ecto_autogenerate and :ecto_autoupdate module attributes at compile time, so that Repo.insert/1 and Repo.update/1 auto-populate them — matching what Ecto's native timestamps() macro does.

Timestamps sharing the same storage type are grouped into a single registration entry so they receive the same generated value, preserving Ash's match_other_defaults? semantics.

Closes #769

# Contributor checklist

Leave anything that you believe does not apply unchecked.

- [X] I accept the [AI Policy](https://github.com/ash-project/.github/blob/main/AI_POLICY.md), or AI was not used in the creation of this PR.
- [ ] Bug fixes include regression tests
- [ ] Chores
- [ ] Documentation changes
- [X] Features include unit/acceptance tests
- [ ] Refactoring
- [ ] Update dependencies

### CODE REVIEW

File: lib/ash/resource/schema.ex [hunk 1]
```diff
@@ -383,4 +387,75 @@ defmodule Ash.Schema do
...
+  end
+
+  @doc false
+  def timestamp_attribute?(attr) do
+    storage_type = resolve_storage_type(attr)
+
+    ecto_datetime_type?(storage_type) &&
+      attr.writable? == false &&
+      (is_function(attr.default) || match?({_, _, _}, attr.default)) &&
+      attr.match_other_defaults? == true &&
```
Comment (zachdaniel) [inline lib/ash/resource/schema.ex]: What we would want to do is not reject things that `match_other_defaults? == false`, but just include those as a group on their own, that way they would be included.

File: lib/ash/resource/schema.ex [hunk 2]
```diff
@@ -383,4 +387,75 @@ defmodule Ash.Schema do
...
+      attr.allow_nil? == false
+  end
+
+  # Resolves the underlying Ecto storage type atom for an attribute by
+  # initializing its type constraints first. This is necessary because
+  # Ash NewTypes (like UtcDatetimeUsec) need their subtype constraints
+  # merged before storage_type returns the correct atom.
+  defp resolve_storage_type(attr) do
+    case Ash.Type.init(attr.type, attr.constraints) do
```
Comment (zachdaniel) [inline lib/ash/resource/schema.ex]: hmm....this *should* already be done I think?

**Comment by RylandBangerter85** [comment]
Okay I should have fixed those two things now

File: lib/ash/resource/schema.ex [hunk 3]
```diff
@@ -383,4 +387,86 @@ defmodule Ash.Schema do
...
+        {[attr.name], {Ecto.Schema, :__timestamps__, [storage_type]}}
+      )
+    end)
+  end
+
+  @doc false
+  def timestamp_attribute?(attr) do
+    ecto_datetime_type?(Ash.Type.storage_type(attr.type, attr.constraints)) &&
+      attr.writable? == false &&
+      (is_function(attr.default) || match?({_, _, _}, attr.default)) &&
```
Comment (zachdaniel) [inline lib/ash/resource/schema.ex]: The attr.default would need to be specifically `&DateTime.utc_now/0` to apply here.

**Comment by RylandBangerter85** [comment]
Okay! The timestamp_attribute? check now specifically requires attr.default == &DateTime.utc_now/0 instead of accepting any function or MFA default.

**Comment by zachdaniel** [comment]
🚀 Thank you for your contribution! 🚀
